"""PaiCLI Python — a local coding-agent harness with three execution modes."""

from .agent import Agent, AgentLoopError
from .agents import (
    AgentBudget,
    AgentLoopEngine,
    AgentOutcome,
    BudgetExitReason,
    CompletionDecision,
    CompletionPolicy,
    FinishReason,
    NonEmptyCompletionPolicy,
    RunStatus,
    ToolObservingCompletionPolicy,
    ToolRuntime,
)
from .bootstrap import (
    ApplicationRuntime,
    ReactRuntime,
    build_application_runtime,
    build_react_runtime,
)
from .evaluation import (
    EvalSuite,
    EvalTask,
    EvaluationReport,
    EvaluationRunner,
    compare_reports,
    load_suite,
)
from .execution import CoordinatedRun, RunCoordinator
from .llm_client import (
    ChatResponse,
    LlmClient,
    LlmClientFactory,
    LlmError,
    OpenAICompatibleClient,
    RetryingLlmClient,
    ToolCall,
    unwrap_llm_client,
)
from .managed_memory import ManagedLongTermMemory, MemoryStatus
from .memory import ConversationHistoryCompactor, LongTermMemory, MemoryManager
from .observability import (
    ModelPricing,
    PricingCatalog,
    RunBudget,
    RunBudgetExceeded,
    RunLimits,
    TraceStore,
)
from .orchestration import (
    AggregationResult,
    DeterministicResultAggregator,
    LlmResultAggregator,
    OrchestrationMode,
    OrchestrationResult,
    OrchestrationStatus,
    PlanModeRuntime,
    TaskRunRecord,
    TeamModeRuntime,
)
from .planning import (
    DagScheduler,
    ExecutionPlan,
    LlmPlanner,
    PlanExecuteAgent,
    PlanGenerationError,
    PlanReviewAction,
    PlanReviewDecision,
    PlanValidationError,
    PlanValidator,
    StaticPlanner,
    Task,
    TaskConcurrencyPolicy,
    TaskStatus,
    TaskType,
)
from .rag import (
    CodeChunk,
    CodeChunker,
    CodeIndex,
    EmbeddingClient,
    OpenAICompatibleEmbeddingClient,
    SearchResult,
    VectorStore,
)
from .review import ReviewResult, ReviewRun, ReviewVerdict, ReviewerAgent
from .safety import RollbackPolicy, WorkspaceRunGuard
from .state import RunStateStore, StoredRun, StoredRunStatus
from .subagents import (
    DependencyResult,
    SubAgent,
    SubAgentFactory,
    SubAgentRole,
    TaskCompletionPolicy,
    TaskPacket,
    ToolScope,
)
from .tools import (
    ConcurrencyPolicy,
    ResourceAccess,
    ResourceMode,
    ScopedToolRuntime,
    ToolErrorType,
    ToolRegistry,
    ToolResult,
    ToolRisk,
    ToolSideEffect,
    ToolSpec,
)

__version__ = "1.0.0"

__all__ = [
    "Agent",
    "AgentBudget",
    "AgentLoopEngine",
    "AgentLoopError",
    "AgentOutcome",
    "AggregationResult",
    "ApplicationRuntime",
    "BudgetExitReason",
    "ChatResponse",
    "CodeChunk",
    "CodeChunker",
    "CodeIndex",
    "CompletionDecision",
    "CompletionPolicy",
    "ConcurrencyPolicy",
    "CoordinatedRun",
    "ConversationHistoryCompactor",
    "DagScheduler",
    "DependencyResult",
    "DeterministicResultAggregator",
    "EmbeddingClient",
    "EvalSuite",
    "EvalTask",
    "EvaluationReport",
    "EvaluationRunner",
    "ExecutionPlan",
    "FinishReason",
    "LlmClient",
    "LlmClientFactory",
    "LlmError",
    "LlmPlanner",
    "LlmResultAggregator",
    "LongTermMemory",
    "ManagedLongTermMemory",
    "MemoryManager",
    "MemoryStatus",
    "ModelPricing",
    "NonEmptyCompletionPolicy",
    "OpenAICompatibleClient",
    "OpenAICompatibleEmbeddingClient",
    "OrchestrationMode",
    "OrchestrationResult",
    "OrchestrationStatus",
    "PlanExecuteAgent",
    "PlanGenerationError",
    "PlanModeRuntime",
    "PlanReviewAction",
    "PlanReviewDecision",
    "PlanValidationError",
    "PlanValidator",
    "PricingCatalog",
    "ReactRuntime",
    "ResourceAccess",
    "ResourceMode",
    "RetryingLlmClient",
    "ReviewResult",
    "ReviewRun",
    "ReviewVerdict",
    "ReviewerAgent",
    "RollbackPolicy",
    "RunBudget",
    "RunBudgetExceeded",
    "RunCoordinator",
    "RunLimits",
    "RunStateStore",
    "RunStatus",
    "ScopedToolRuntime",
    "SearchResult",
    "StaticPlanner",
    "StoredRun",
    "StoredRunStatus",
    "SubAgent",
    "SubAgentFactory",
    "SubAgentRole",
    "Task",
    "TaskCompletionPolicy",
    "TaskConcurrencyPolicy",
    "TaskPacket",
    "TaskRunRecord",
    "TaskStatus",
    "TaskType",
    "TeamModeRuntime",
    "ToolCall",
    "ToolErrorType",
    "ToolObservingCompletionPolicy",
    "ToolResult",
    "ToolRisk",
    "ToolRuntime",
    "ToolRegistry",
    "ToolScope",
    "ToolSideEffect",
    "ToolSpec",
    "TraceStore",
    "VectorStore",
    "WorkspaceRunGuard",
    "build_application_runtime",
    "build_react_runtime",
    "compare_reports",
    "load_suite",
    "unwrap_llm_client",
    "__version__",
]
