"""PaiCLI Python: a coding agent built across 22 learning phases."""

from .agent import Agent, AgentLoopError
from .agents import (
    AgentBudget,
    AgentLoopEngine,
    AgentOutcome,
    BudgetExitReason,
    CompletionDecision,
    CompletionPolicy,
    FinishReason,
    NonEmptyCompletionPolicy,
    RunStatus,
    ToolObservingCompletionPolicy,
    ToolRuntime,
)
from .bootstrap import (
    ApplicationRuntime,
    ReactRuntime,
    build_application_runtime,
    build_react_runtime,
)
from .llm_client import ChatResponse, OpenAICompatibleClient, ToolCall
from .memory import ConversationHistoryCompactor, LongTermMemory, MemoryManager
from .orchestration import (
    AggregationResult,
    DeterministicResultAggregator,
    LlmResultAggregator,
    OrchestrationMode,
    OrchestrationResult,
    OrchestrationStatus,
    PlanModeRuntime,
    PlanReviewAction,
    PlanReviewDecision,
    PlanReviewHandler,
    TaskRunRecord,
    TeamModeRuntime,
)
from .planning import (
    DagScheduler,
    ExecutionPlan,
    LlmPlanner,
    PlanExecuteAgent,
    PlanGenerationError,
    PlanValidationError,
    PlanValidator,
    StaticPlanner,
    Task,
    TaskConcurrencyPolicy,
    TaskStatus,
    TaskType,
)
from .review import ReviewResult, ReviewRun, ReviewVerdict, ReviewerAgent
from .subagents import (
    DependencyResult,
    SubAgent,
    SubAgentFactory,
    SubAgentRole,
    TaskCompletionPolicy,
    TaskPacket,
    ToolScope,
)
from .tools import (
    ConcurrencyPolicy,
    ResourceAccess,
    ResourceMode,
    ScopedToolRuntime,
    ToolErrorType,
    ToolRegistry,
    ToolResult,
    ToolRisk,
    ToolSideEffect,
    ToolSpec,
)

__version__ = "0.22.0"

__all__ = [
    "Agent",
    "AggregationResult",
    "ApplicationRuntime",
    "AgentBudget",
    "AgentLoopEngine",
    "AgentLoopError",
    "AgentOutcome",
    "BudgetExitReason",
    "ChatResponse",
    "ConcurrencyPolicy",
    "ConversationHistoryCompactor",
    "DependencyResult",
    "DeterministicResultAggregator",
    "DagScheduler",
    "CompletionDecision",
    "CompletionPolicy",
    "ExecutionPlan",
    "FinishReason",
    "LlmPlanner",
    "LlmResultAggregator",
    "LongTermMemory",
    "MemoryManager",
    "NonEmptyCompletionPolicy",
    "OrchestrationMode",
    "OrchestrationResult",
    "OrchestrationStatus",
    "OpenAICompatibleClient",
    "PlanExecuteAgent",
    "PlanModeRuntime",
    "PlanReviewAction",
    "PlanReviewDecision",
    "PlanReviewHandler",
    "PlanGenerationError",
    "PlanValidationError",
    "PlanValidator",
    "ReactRuntime",
    "ReviewResult",
    "ReviewRun",
    "ReviewVerdict",
    "ReviewerAgent",
    "ResourceAccess",
    "ResourceMode",
    "RunStatus",
    "ScopedToolRuntime",
    "StaticPlanner",
    "SubAgent",
    "SubAgentFactory",
    "SubAgentRole",
    "Task",
    "TaskCompletionPolicy",
    "TaskConcurrencyPolicy",
    "TaskPacket",
    "TaskRunRecord",
    "TaskStatus",
    "TaskType",
    "TeamModeRuntime",
    "ToolCall",
    "ToolErrorType",
    "ToolResult",
    "ToolObservingCompletionPolicy",
    "ToolRisk",
    "ToolRuntime",
    "ToolRegistry",
    "ToolScope",
    "ToolSideEffect",
    "ToolSpec",
    "build_application_runtime",
    "build_react_runtime",
    "__version__",
]
